<?php

declare(strict_types=1);

namespace BikeCoders\MapBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260101000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create map_source table for BikeCodersMapBundle';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE map_source (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, region VARCHAR(255) NOT NULL, version VARCHAR(255) NOT NULL, s3_key VARCHAR(255) NOT NULL, source_url VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_active BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN map_source.created_at IS \'(DC2Type:datetime_immutable)\'');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE map_source');
    }
}
